services:
  db:
    image: postgres:16.4
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "54320:5432"
    networks:
      - app-network
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: tg_bot_api
    environment:
      TELEGRAM_API_ID: "20065413"
      TELEGRAM_API_HASH: "db6784784f0c6974d0f57d5ae7866e25"
      TELEGRAM_LOCAL: 1
      TELEGRAM_STAT: 1
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - app-network
  php:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    image: php_app
    container_name: app
    environment:
      TELEGRAM_BOT_TOKEN: "7866534109:AAEm2hMQ8iDpwlX_OtcDbA0bKK57Vedpn-w"
      DB_CONNECTION: "pgsql"
      DB_HOST: "postgres_db"
      DB_PORT: 5432
      DB_DATABASE: "postgres"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "mysecretpassword"
    volumes:
      - ./code:/data/mysite.local
      - php_socket:/var/run/php
    networks:
      - app-network
  webserver:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    image: ws
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local
      - php_socket:/var/run/php
    depends_on:
      - php
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  php_socket:
  telegram-bot-api-data:
